language: node_js
node_js:
- 8.12.0
cache:
  yarn: true
before_install: yarn global add greenkeeper-lockfile@1
install:
- yarn install
before_script: greenkeeper-lockfile-update
script:
- yarn lint
- yarn coverage
- yarn codacy
after_script: greenkeeper-lockfile-upload
before_deploy:
- yarn build
deploy:
  provider: npm
  email: bartosz.polanczyk@gmail.com
  api_key:
    secure: DjXFA1/bK1jF9wTLW0FhEoXx77QFnBPaGYUhyl27M0RBQI2XIeYnI7sFwmezzoTZz314cbERsjpVPX6G8V2Ih/VHLCgz2Snxa/SFxq6Gz3qKUe755Lbg+OwQFDR5k86rjqd/uX2sCjwvgD+uo2iKxy9zP0Dp/f0G88pcP6AHL8wsg6P7NDtF7ySxDJxWlNW7QKISVUSozX0LpfhsJDSEyKhOIplqyitI++0X5kuVlgkc+THG6PQWzF4y8CLfgk0IW33T1Kl6DsZV4faj2L9nBSU2r/24NraIssc9NwO/6ycvJibDDbY5X7P0mxiXm64Y/KmL0uD1s5gPYjA7jWPaFybFL5ab5MUJOJJ60k3c7gsM36Ld1BkaWVCPv25MuOy+dhyA+Szd7xt7vCROUkpQ7t9543oodszLtLy4oOTW9OHaiXjQMAS76ds8aK7EU6XN5iijubLbRBqovjluQ+RDLfxeYGN8FLKQK3Ofbal+zetvW0q10jYoiGS5qiYHvI5U7hxYu3h6ioSY8FTxQ+3HemBRD+DGHya7GqDCLACZGAYWSUzE42boYcZfYt29qk4d8bqAZ/bZpPd1UflsVG8qzBg87huqbe8x1NEPx5I5B7Cwan8gi93Q0StFEwosyRyEaNeVnFe2xXvrGxU+EXvdl8W1mxzfNj7YH4H+So2BsF4=
  on:
    all_branches: true
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: qh9a7fe3DBXKSYv+qW6BvhlhLcpvj6/RppxfKzqOwwEzDtekYh9oQPTnLWcpcq+pU8MYhy6MEhfqTswphYSrInzpRJpFitW9H+nc9s9MXD7T8tzcgv1tCABw1pImgz1Jy1vJHdcJDIHqIsplQaqYV9yLlFOyspdgTWkczPjookLfqr+B5QwnaAweh0tUcUlEw9VFz/2PnQXNFdhVTCsIE67VcaDsUw0N/ZNP9M4PPOZuiAQJPocv/A1yUJf/rEAv2Ve8xfszwKXIB5QirkJtZlnszrELfLa5tcsNkmpFCKZ94/I1rNF/qMeODH1HQ1GZZpKP1V+n+teaipvcfiwg9gaRmTo/nDGsHGcQ04Lk9F7wrO6utYqrR7JDf0bMSDtR2P55Tx7RZgg+Oyi+MNZAA4mPiFpo8K/Cx67E3gBct/dj1bJRGF3PCF0kaSNAfeFe4m1OcFmqEeYU6WtxvXwxp+/szS4bDopnSWbeiNiDVqOipvBACPCdhlcKIKHeEGOcRLYjMXxzxbm7TY1XufN04klvvY2GQJdBGDw8Yl7FA8kZUwAZ/eijkYGbK/Zf7lN4P3Hd/ldClZSFCi4OzvA0POEjU0L+8NV1u18yFTGyDpJ2IebjyUKkZYAHbLJ4F8eN8Psxd6L96QQZHZH8JBhuZ3ZhIAmC7ZxfNKOYgRnnkhA=
  - secure: oYXhRRTiH/w8JTL/eW2gXQ3XHjhgTOdEBTzSUSGBpy3cyYaX9lqvaxvBWuydOp85W+9UYsciNes/YnJo/oQYp6tYM7Ncz/ehV0ElzGW8KIfRt5s1R8P2bq0MXGeQbpzhvtPAURHLs4TCTZxPfsTfMAiuSlZZ26oK8Jwam5d9/uTGFANlGiL3L0woiO+oSA90bJi6Y84R5fBvc7Rbluji9nEDWdScfxxqsYTeg58p6ioMTkBYHBU9NSpdXXznGNWousV5kb8sYHUqQ3C+SZK9xsOcT140k+rot8ofTZvJPob/YM/iDMYkSfB7dusRqKu5uKpnfMW3OhwapjWUXRWdA6S72ANC/x5r1gChMJKB+uZxOwHAuVLAnIG32di7qQfRASvpoGloJX839eUJfv6PTx9NEkMw3pABg9Levo4VhF4v0Olm+PVno08GgEIMcGc58ZsCnC5VdTmuLms9WDt3WI12ys/4sbieaMSTlNWmKG3xcd261C1VMsb4S+fgyhB27SkcSgOR5SQ5CLnJJWej9AoHNGNvOwOpKEaXfgURn3yxox0vA+8Qq9ssEnROlTu+SRnYQ8PF5x3G2RLJxmLhZfCQQt+pEmQH3vjQviTV071pk8AbcbLGLqzHKnBCa4Cu2Dz9BIB984bPj2YByJkLH2b1KL49apvxAS2srNtVarA=
